---
- hosts: localhost
  become: true
  gather_facts: false

  vars_files:
    - vars.yaml

  tasks:

    - name: Copy config.yaml
      copy:
        src: ur_force_record_config.yaml
        dest: "/home/{{ custom_username }}/Desktop/ur_force_record_config.yaml"
        owner: "{{custom_username}}"
        group: users
        force: no

    - name: Ensure docker daemon is running
      service:
        name: docker
        state: started

    - include_tasks: app_setup.yaml
      loop: "{{ docker_image_names }}"
