---
- hosts: localhost
  become: true
  gather_facts: false

  vars_files:
    - vars.yaml

  tasks:
    - name: Adding user to dialout
      user:
        name: "{{ custom_username }}"
        groups: dialout
        append: yes

    - name: Copy config.yaml
      copy:
        src: ur_force_record_config.yaml
        dest: "/home/{{ custom_username }}/Desktop/ur_force_record_config.yaml"
        owner: "{{custom_username}}"
        group: users
        force: no

    - name: Ensure docker daemon is running
      service:
        name: docker
        state: started

    - include_tasks: app_setup.yaml
      loop: "{{ docker_image_names }}"

    - name: Create file to refresh desktop
      file:
        path: "/home/{{ custom_username }}/Desktop/refresh.desktop"
        state: touch
        force: yes

    - name: Remove file to refresh desktop
      file:
        path: "/home/{{ custom_username }}/Desktop/refresh.desktop"
        state: absent
        force: yes
